name: slack

on: 
  workflow_call:
    secrets:
      SLACK_URL:
        required: true


env:
  # For all events
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_URL: ${{ github.event.repository.html_url }}
  SHA: ${{ github.sha }}
  EVENT_NAME: ${{ github.event_name }}
  ACTOR_URL: ${{ github.event.sender.html_url }}
  ACTOR: ${{ github.actor }}
  
  # for PR
  PR_URL: ${{ github.event.pull_request._links.html.href }}
  PR_TITLE: ${{ github.event.pull_request.title }}

  # for merge 
  PR_SUMMARY: ${{ github.event.head_commit.message }}

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
    - name: slack
      run: >
       IN="${{ env.PR_SUMMARY }}" &&  MESSAGE=${IN##*$'\n'} && echo $MESSAGE && echo ${{ env.MESSAGE }} && echo '{"repo": "${{ env.REPO_NAME }}",  "repo_url": "${{ env.REPO_URL }}",  "event": "${{ env.EVENT_NAME}}",  "pr_url": "${{ env.PR_URL }}",  "actor_url": "${{ env.ACTOR_URL }}", "actor": "${{ env.ACTOR }}", "pr_title": "${{ env.PR_TITLE }}", "pr_summary": "$MESSAGE"}'
   
   
   
  # curl -X POST ${{ secrets.SLACK_URL }} 
  # -H "Content-Type: application/json" 
  # --data '{"repo": "${{ env.REPO_NAME }}",  "repo_url": "${{ env.REPO_URL }}",  "event": "${{ env.EVENT_NAME}}",  "pr_url": "${{ env.PR_URL }}",  "actor_url": "${{ env.ACTOR_URL }}", "actor": "${{ env.ACTOR }}", "pr_title": "${{ env.PR_TITLE }}", "pr_summary": "$MESSAGE"}'